### ISSUE TITLE
Account 'data' on windows

### ISSUE THREAD

**Issue by kuhlkrein** [GazePlay/GazePlay#948] opened 2019-12-04 20:53 UTC
I noticed that with Windows on the account homepage we have the account 'data' that should not appear here. It's propbably due to the fact that we're listing all the folder contained in a given directory, containing this 'data' folder

**Comment by kuhlkrein** [comment] 2019-12-17 13:09
I can't reproduce, maybe it was just due to an unexpected copy-paste...

**Comment by Tohaker** [comment] 2020-01-03 20:06
I can't reproduce this either. I reckon we should close this and open a new issue with logs if this happens again - especially as we now have more logging when finding the profiles.

**Closed** 2020-01-03 20:31 UTC
Labels: check if fixed
