### ISSUE TITLE
Release Gazeplay 1.7

### ISSUE THREAD

**Issue by kuhlkrein** [GazePlay/GazePlay#1017] opened 2020-01-14 10:37 UTC
Hello @YannRobert and @Tohaker , 
@schwabdidier would like to release Gazeplay 1.7 soon and he would like to know if you think that the current verion is stable enough to do so ? 

If yes, could you please try to fill the GazePlay-1.7.md file ( #993 ), or add your contribution as comment here, so I can add it to the file.

I see that there is a pending pull request #1013 aiming to fix #1011 , we need to integrate it to the new verion too right ?

**Comment by Tohaker** [comment] 2020-01-14 10:45
I think the most notable issues have been fixed (at least, when #1013 is merged) so I'd be confident with a 1.7 release. 
Whilst it may not be my place to say, I am concerned with the lack of tests written for new code. If for nothing else than making sure we don't regress existing behaviour with new features. I've been adding in tests in my PRs, which (for the most part) can run in CI and should serve for a starting point for other tests to be written. We'd be much more confident with proof the code works as intended.

**Comment by schwabdidier** [comment] 2020-01-14 17:07
For information, I have never been able to publish a version 1.X which was not followed by a version 1.X.1 with (strong) bugs resolved from people's computer. But at that time, I was not with all of you

**Comment by Tohaker** [comment] 2020-01-14 17:27
That may be fixed since we're using the Gradle Plugin now, but we could try it first on a fork and see if it releases correctly?

**Closed** 2020-01-19 15:49 UTC
