### ISSUE TITLE
Sounds not played on linux with zulu-11-amd64

### ISSUE THREAD

**Issue by kuhlkrein** [GazePlay/GazePlay#1151] opened 2020-03-23 10:48 UTC
**Describe the bug**
The sounds files cant be played due to libavplugin.so': libavcodec.so.55 not found in my zulu-11-amd64 JRE

**To Reproduce**
install zulu-11-amd64 with fx JRE and launch the gazeplay-linux.sh 

**Expected behavior**
Should be able to read the mp3 files and play the sounds

**Context:**
 - Linux
 - GazePlay Version: 1.7.2

**Additional context**
```
** (java:5682): WARNING **: Failed to load plugin '/usr/lib/jvm/zulu-11-amd64/lib/libavplugin.so': libavcodec.so.55: Ne peut ouvrir le fichier d'objet partagé: Aucun fichier ou dossier de ce type
2020-03-23 13:29:04,896 ERROR net.gazeplay.commons.utils.games.BackgroundMusicManager - error while loading media file:/home/sebastien/GazePlay/music/songidea(copycat)_0.mp3, type : UNKNOWN
```

**Comment by kuhlkrein** [comment] 2020-03-23 10:50
@Tohaker do you think it will be fixed with the JRE PR ? I had to install my own zulu JRE as you can see here in order to test GazePlay on linux, I think I missed the given Library in my version

**Comment by Tohaker** [comment] 2020-03-23 10:51
I'm not sure, I'd have to check myself on my Linux. What happens if you use the dist on S3? That should have the correct Linux Zulu JRE in it

**Comment by kuhlkrein** [comment] 2020-03-23 11:03
it's the one I'm using but it still wants to use my own java version...

**Comment by kuhlkrein** [comment] 2020-03-23 11:23
Ok I finally managed to install openJDK 11 and it works with it, but yeah, my system is not using the JRE provided in the dist on S3

**Comment by Tohaker** [comment] 2020-03-23 14:04
What does your path look like when you run `gazeplay-linux.sh`? It sounds like it's just not finding the included JRE

**Comment by kuhlkrein** [comment] 2020-03-24 10:42
Hi @Tohaker , which path ?
Actually `/usr/lib/jvm/zulu-11-amd64/lib/libavplugin.so` exists , but I think the problem was due to the  `libavcodec.so.55` part.

**Comment by Tohaker** [comment] 2020-03-24 10:43
The `PATH` environment variable. It should be printed to the console when you run the bash file

**Comment by kuhlkrein** [comment] 2020-03-24 10:48
`WORKING_DIR = /home/sebastien/Téléchargements/gazeplay-project-linux-x64-1.7.2-SNAPSHOT/bin
SCRIPT_DIR = .
LIB_DIR = ./../lib
LIB_DIR_RELATIVE = ../lib
JAVA_HOME = ./../lib/jre/bin
Executing command line: java -cp "./../lib/animal-sniffer-annotations-1.18.jar:./../lib/annotations-13.0.jar:./../lib/awaitility-4.0.1.jar:./../lib/checker-qual-2.8.1.jar:./../lib/classgraph-4.8.52.jar:./../lib/commons-io-2.5.jar:./../lib/commons-lang3-3.9.jar:./../lib/commons-logging-api-1.1.jar:./../lib/error_prone_annotations-2.3.2.jar:./../lib/eyetribe-java-0.9.77.jar:./../lib/failureaccess-1.0.1.jar:./../lib/gazeplay-1.7.2-SNAPSHOT.jar:./../lib/gazeplay-commons-1.7.2-SNAPSHOT.jar:./../lib/gazeplay-games-1.7.2-SNAPSHOT.jar:./../lib/gazeplay-games-commons-1.7.2-SNAPSHOT.jar:./../lib/gazeplay-melordi-1.7.2-SNAPSHOT.jar:./../lib/gazeplay-picto-pick-1.7.2-SNAPSHOT.jar:./../lib/gson-2.8.6.jar:./../lib/guava-28.1-jre.jar:./../lib/hamcrest-2.1.jar:./../lib/j2objc-annotations-1.3.jar:./../lib/jakarta.annotation-api-1.3.5.jar:./../lib/javafx-base-11.0.2.jar:./../lib/javafx-base-11.0.2-linux.jar:./../lib/javafx-controls-11.0.2.jar:./../lib/javafx-controls-11.0.2-linux.jar:./../lib/javafx-graphics-11.0.2.jar:./../lib/javafx-graphics-11.0.2-linux.jar:./../lib/javafx-media-11.0.2.jar:./../lib/javafx-media-11.0.2-linux.jar:./../lib/javafx-swing-11.0.2-linux.jar:./../lib/javafx-web-11.0.2-linux.jar:./../lib/javassist-3.21.0-GA.jar:./../lib/javax.servlet-api-4.0.1.jar:./../lib/jave-all-deps-2.5.0.jar:./../lib/jave-core-2.5.0.jar:./../lib/jave-nativebin-linux32-2.5.0.jar:./../lib/jave-nativebin-linux64-2.5.0.jar:./../lib/jave-nativebin-osx64-2.5.0.jar:./../lib/jave-nativebin-win32-2.5.0.jar:./../lib/jave-nativebin-win64-2.5.0.jar:./../lib/jcl-over-slf4j-1.7.29.jar:./../lib/jmf-2.1.1e.jar:./../lib/jre/lib/javafx-swt.jar:./../lib/jre/lib/jrt-fs.jar:./../lib/jre/zulu11.35.15-ca-fx-jre11.0.5-linux_x64/lib/javafx-swt.jar:./../lib/jre/zulu11.35.15-ca-fx-jre11.0.5-linux_x64/lib/jrt-fs.jar:./../lib/jsr305-3.0.2.jar:./../lib/jul-to-slf4j-1.7.29.jar:./../lib/listenablefuture-9999.0-empty-to-avoid-conflict-with-guava.jar:./../lib/log4j-1.2.17.jar:./../lib/log4j-api-2.12.1.jar:./../lib/log4j-over-slf4j-1.7.29.jar:./../lib/log4j-to-slf4j-2.12.1.jar:./../lib/logback-classic-1.2.3.jar:./../lib/logback-core-1.2.3.jar:./../lib/owner-1.0.10.jar:./../lib/owner-java8-1.0.10.jar:./../lib/picocli-4.0.4.jar:./../lib/picocli-spring-boot-starter-4.0.4.jar:./../lib/reflections-0.9.11.jar:./../lib/rxtx-2.1.7.jar:./../lib/screen-recorder-0.0.3.jar:./../lib/slf4j-api-1.7.29.jar:./../lib/snakeyaml-1.25.jar:./../lib/spring-aop-5.2.1.RELEASE.jar:./../lib/spring-beans-5.2.1.RELEASE.jar:./../lib/spring-boot-2.2.1.RELEASE.jar:./../lib/spring-boot-autoconfigure-2.2.1.RELEASE.jar:./../lib/spring-boot-starter-2.2.1.RELEASE.jar:./../lib/spring-boot-starter-logging-2.2.1.RELEASE.jar:./../lib/spring-context-5.2.1.RELEASE.jar:./../lib/spring-core-5.2.1.RELEASE.jar:./../lib/spring-expression-5.2.1.RELEASE.jar:./../lib/spring-jcl-5.2.1.RELEASE.jar:./../lib/sysout-over-slf4j-1.0.2.jar:./../lib/TobiiStreamEngineForJava-4.0.jar:./../lib/video-recorder-core-2.0.jar:./../lib/zt-exec-1.10.jar:" -Xms256m -Xmx1g -Dlogging.appender.console.level=WARN net.gazeplay.GazePlayLauncher
`

**Comment by kuhlkrein** [comment] 2020-03-24 10:50
It should not be ./../lib/jre/zulu11.35.15-ca-fx-jre11.0.5-linux_x64/bin instead of ./../lib/jre/bin ?

**Comment by Tohaker** [comment] 2020-03-24 10:54
It depends what's in your distribution. The latest one should have be `../../lib/jre/bin` but if you've got the broken version it won't work

**Comment by kuhlkrein** [comment] 2020-03-24 10:58
Actually I have something in both ` ./../lib/jre/bin` and in ` ./../lib/jre/zulu11.35.15-ca-fx-jre11.0.5-linux_x64/bin` . I will try to see if it's due to a broken version.

**Comment by Tohaker** [comment] 2020-03-24 11:14
I just built and packaged from master on my Ubuntu machine and it worked first time. I'm unsure why there are two JREs present, I definitely fixed this last week.

**Comment by kuhlkrein** [comment] 2020-03-24 11:32
Ok perfect then I think I just have an older version, it's still downloading, I have a bad wifi here ...

**Comment by kuhlkrein** [comment] 2020-03-24 12:31
@Tohaker , I think I don't get the way it works, if I have no java on my machine, should gazeplay still work with the JRE in the distribution ? Because for me it gives me java not found. I still have to install a valid version of openJDK11 on my computer to make it work

**Comment by Tohaker** [comment] 2020-03-24 12:34
Yeah, because Java on your machine is just a folder with the binaries, and the JAVA_HOME variable set. If we change where the folder is, it works in exactly the same way

**Comment by kuhlkrein** [comment] 2020-03-24 13:42
Ok so then there is still a problem for me on linux

**Comment by kuhlkrein** [comment] 2020-03-24 14:02
@Tohaker I found a problem:
I changed
```
JAVA_HOME=${LIB_DIR}/jre/bin

echo "JAVA_HOME = ${JAVA_HOME}"
```

by
```
JAVA_HOME=${LIB_DIR}/jre

echo "JAVA_HOME = ${JAVA_HOME}"

export PATH=$JAVA_HOME/bin:$PATH

echo "PATH = ${PATH}"
```

I have no java installed on my machine and it works (except for the sound...)

**Comment by kuhlkrein** [comment] 2020-03-24 14:13
Edit: I just checked an in the windows .bat file we also have 
```
**SET JAVA_HOME=..\lib\jre
SET PATH=%JAVA_HOME%\bin;%PATH%**;%LocalAppData%\TobiiStreamEngineForJava\lib\tobii\x64
```

**Comment by Tohaker** [comment] 2020-03-24 14:15
Good spot, that edit you made will make sure the JAVA_HOME is applied to the PATH. I will try your changes to replicate it

**Comment by kuhlkrein** [comment] 2020-03-24 14:17
Btw, why are we using Zulu and not openJDK ? the sound seems to work with openJDK for me but not with Zulu

**Comment by Tohaker** [comment] 2020-03-24 14:17
Zulu IS OpenJDK - it's just a different vendor that includes the JavaFX libraries in a single download.

**Comment by Tohaker** [comment] 2020-03-24 14:43
When I replace the Zulu JavaFX JRE with the plain Zulu JavaFX JRE, it all works.

**Comment by kuhlkrein** [comment] 2020-03-24 14:47
Nice ! :) And there is no problem with javaFX after that ?

**Comment by kuhlkrein** [comment] 2020-03-24 15:03
As I was supposing, if we remove the javafx part then I have:
```
2020-03-24 17:32:38,826 ERROR com.sun.prism.GraphicsPipeline - Graphics Device initialization failed for :  es2, sw
2020-03-24 17:32:38,827 ERROR com.sun.javafx.tk.quantum.QuantumRenderer - Error initializing QuantumRenderer: no suitable pipeline found
2020-03-24 17:32:38,828 ERROR java.lang.Throwable - java.lang.RuntimeException: java.lang.RuntimeException: Error initializing QuantumRenderer: no suitable pipeline found

```

**Comment by Tohaker** [comment] 2020-03-24 15:48
Thats interesting, are you sure it's using the right JRE? I don't get that error with the same non-JFX JRE

**Comment by kuhlkrein** [comment] 2020-03-24 15:53
But maybe you have javaFX installed somewhere else ? 
I have no other JRE on this pc so it can be only this one...

**Comment by kuhlkrein** [comment] 2020-03-24 15:55
And there are some javafx jar lib so I don't get why i have this error

**Comment by Tohaker** [comment] 2020-03-24 15:56
Ah, well that makes sense. I must have had JavaFX on my classpath. This is why we needed the JRE with JFX... 
When I looked up the error, it seems like `libavcodec` v55 is out of date and has been discontinued in Java. I can't figure out why it tries to use it

**Comment by Tohaker** [comment] 2020-03-24 15:57
The issue is that you need the JavaFX modules in the JRE, which is why I chose Zulu as it's already there

**Comment by kuhlkrein** [comment] 2020-03-24 15:58
Yes from what I've seen on the web it shoud be v59 or something like this now...
Can it be related to my gradle build somehow ?

**Comment by Tohaker** [comment] 2020-03-24 16:04
Nothing to do with Gradle, it's Ubuntu making it difficult for us

**Comment by Tohaker** [comment] 2020-03-24 16:06
Try to update the libavcodec and see if it helps

**Comment by Tohaker** [comment] 2020-03-25 11:47
Let's close this out now that the PR has been merged.

**Closed by Tohaker** 2020-03-25 11:47 UTC
Labels: bug
